<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" ignored="0" total="7" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="UI Tests" duration-ms="120" started-at="2021-07-26T18:04:59 IST" finished-at="2021-07-26T18:04:59 IST">
    <groups>
      <group name="Regression1">
        <method signature="DependenciesInTestNG.test1()[pri:0, instance:com.test.TestNG.DependenciesInTestNG@17579e0f]" name="test1" class="com.test.TestNG.DependenciesInTestNG"/>
        <method signature="DependenciesInTestNG.test2()[pri:0, instance:com.test.TestNG.DependenciesInTestNG@17579e0f]" name="test2" class="com.test.TestNG.DependenciesInTestNG"/>
        <method signature="DependenciesInTestNG.test5()[pri:0, instance:com.test.TestNG.DependenciesInTestNG@17579e0f]" name="test5" class="com.test.TestNG.DependenciesInTestNG"/>
      </group> <!-- Regression1 -->
    </groups>
    <test name="Functional Testing" duration-ms="120" started-at="2021-07-26T18:04:59 IST" finished-at="2021-07-26T18:04:59 IST">
      <class name="com.test.TestNG.DependenciesInTestNG">
        <test-method status="FAIL" signature="test1()[pri:0, instance:com.test.TestNG.DependenciesInTestNG@17579e0f]" name="test1" duration-ms="17" started-at="2021-07-26T18:04:59 IST" finished-at="2021-07-26T18:04:59 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.test.TestNG.DependenciesInTestNG.test1(DependenciesInTestNG.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="test2()[pri:0, instance:com.test.TestNG.DependenciesInTestNG@17579e0f]" name="test2" duration-ms="2" started-at="2021-07-26T18:04:59 IST" finished-at="2021-07-26T18:04:59 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="PASS" signature="test5()[pri:0, instance:com.test.TestNG.DependenciesInTestNG@17579e0f]" name="test5" duration-ms="3" started-at="2021-07-26T18:04:59 IST" finished-at="2021-07-26T18:04:59 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test5 -->
        <test-method status="PASS" signature="test4()[pri:0, instance:com.test.TestNG.DependenciesInTestNG@17579e0f]" name="test4" duration-ms="2" started-at="2021-07-26T18:04:59 IST" depends-on-methods="com.test.TestNG.DependenciesInTestNG.test1" finished-at="2021-07-26T18:04:59 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
        <test-method status="SKIP" signature="test3()[pri:0, instance:com.test.TestNG.DependenciesInTestNG@17579e0f]" name="test3" duration-ms="0" depends-on-groups="Regression1" started-at="2021-07-26T18:04:59 IST" finished-at="2021-07-26T18:04:59 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DependenciesInTestNG.test3()[pri:0, instance:com.test.TestNG.DependenciesInTestNG@17579e0f] depends on not successfully finished methods in group "Regression1"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DependenciesInTestNG.test3()[pri:0, instance:com.test.TestNG.DependenciesInTestNG@17579e0f] depends on not successfully finished methods in group "Regression1"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:101)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method status="SKIP" signature="test6()[pri:0, instance:com.test.TestNG.DependenciesInTestNG@17579e0f]" name="test6" duration-ms="0" started-at="2021-07-26T18:04:59 IST" depends-on-methods="com.test.TestNG.DependenciesInTestNG.test1" finished-at="2021-07-26T18:04:59 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DependenciesInTestNG.test6()[pri:0, instance:com.test.TestNG.DependenciesInTestNG@17579e0f] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DependenciesInTestNG.test6()[pri:0, instance:com.test.TestNG.DependenciesInTestNG@17579e0f] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:101)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test6 -->
        <test-method status="SKIP" signature="test7()[pri:0, instance:com.test.TestNG.DependenciesInTestNG@17579e0f]" name="test7" duration-ms="0" started-at="2021-07-26T18:04:59 IST" depends-on-methods="com.test.TestNG.DependenciesInTestNG.test1" finished-at="2021-07-26T18:04:59 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DependenciesInTestNG.test7()[pri:0, instance:com.test.TestNG.DependenciesInTestNG@17579e0f] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DependenciesInTestNG.test7()[pri:0, instance:com.test.TestNG.DependenciesInTestNG@17579e0f] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:101)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test7 -->
      </class> <!-- com.test.TestNG.DependenciesInTestNG -->
    </test> <!-- Functional Testing -->
  </suite> <!-- UI Tests -->
</testng-results>
